apiVersion: apps/v1
kind: Deployment
metadata:
  name: webase-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webase-server
  template:
    metadata:
      labels:
        app: webase-server
    spec:
      containers:
        - name: webase-server
          image: webase/webase-server
          env:
            - name: WEBASE_SERVER_PORT
              value: "443"
            - name: WEBASE_SERVER_HARBOR_URL
              value: "http://191.8.9.100:5000"
            - name: WEBASE_SERVER_HARBOR_USER
              value: "admin"
            - name: WEBASE_SERVER_HARBOR_PASSWORD
              value: "Harbor12345"
            - name: WEBASE_SERVER_DASHBOARD_URL
              value: "http://webase-dashboard2:9090"
            - name: WEBASE_SERVER_DRONE_URL
              value: "http://tpipe-server:80"
            - name: WEBASE_SERVER_ENABLEHTTPS
              value: "true"
            - name: WEBASE_SERVER_HTTPSCERTFILE
              value: "/etc/webase/ssl/tls.crt"
            - name: WEBASE_SERVER_HTTPSKEYFILE
              value: "/etc/webase/ssl/tls.key"
            - name: WEBASE_SERVER_UI_URL
              value: "http://webase-ui"
            - name: WEBASE_SERVER_GRAFANA_URL
              value: "http://grafana.cattle-prometheus:3000"
            - name: WEBASE_SERVER_MYSQL_ADDRESS
              value: "webase-mysql:3306"
            - name: WEBASE_SERVER_MYSQL_USERNAME
              value: "webase"
            - name: WEBASE_SERVER_MYSQL_PASSWORD
              value: "WebaseQwer1234"
            - name: WEBASE_SERVER_MYSQL_DATABASE
              value: "webase"
            - name: WEBASE_SERVER_HOST
              value: "https://188.8.5.1:38401"
            - name: WEBASE_SERVER_LDAP_USER_STORE
              value: "true"
            - name: WEBASE_SERVER_LDAP_HOST
              value: "openldap"
            - name: WEBASE_SERVER_LDAP_PORT
              value: "389"
            - name: WEBASE_SERVER_LDAP_PASSWORD
              value: "Qwer1234"
            - name: WEBASE_SERVER_LDAP_BASE
              value: "c=webase,dc=cloud"
            - name: WEBASE_SERVER_OIDC_CLIENT_ID
              value: "webase"
            - name: WEBASE_SERVER_OIDC_CLIENT_SECRET
              value: "ZXhhbXBsZS1hcHAtc2VjcmV0"
            - name: WEBASE_SERVER_OIDC_ISSUER_URL
              value: "http://191.8.9.12:35556/dex"
            - name: WEBASE_SERVER_OIDC_ENABLED
              value: "true"
            - name: WEBASE_SERVER_YAML_DIRNAME
              value: "/etc/webase/yaml/"
            - name: WEBASE_SERVER_CASBIN_MODEL
              value: "/etc/webase/casbin/model.conf"
            - name: WEBASE_SERVER_CASBIN_POLICY
              value: "/etc/webase/casbin/policy.csv"
            

          ports:
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: webase-server
spec:
  selector:
    app: webase-server
  type: NodePort
  ports:
  - port: 443
    targetPort: 443
    nodePort: 38401