FROM alpine/helm:3.3.4 as helm
FROM docker/compose:1.27.4
COPY --from=helm /usr/bin/helm /usr/local/bin/helm
RUN echo http://mirrors.aliyun.com/alpine/v3.10/main/ > /etc/apk/repositories && \
    echo http://mirrors.aliyun.com/alpine/v3.10/community/ >> /etc/apk/repositories && \
    apk add openssh-client ca-certificates && sed -ie 's/#   StrictHostKeyChecking ask/   StrictHostKeyChecking no/g' /etc/ssh/ssh_config